const products = [
  // Anime Posters
  {
    id: 1,
    name: "Naruto — Legacy of the Leaf",
    price: 499,
    category: "anime",
    subcategory: "Anime Posters",
    tag: "Bestseller",
    image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=500&fit=crop",
    description: "High-quality Naruto anime poster with stunning artwork. Perfect for room décor and anime fans.",
  },
  {
    id: 2,
    name: "Gojo Satoru — Infinity",
    price: 699,
    category: "anime",
    subcategory: "Anime Posters",
    tag: "New",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&h=500&fit=crop",
    description: "Stunning Gojo Satoru sketch from Jujutsu Kaisen. A must-have for JJK fans.",
  },
  {
    id: 3,
    name: "Itachi Uchiha — Sharingan",
    price: 599,
    category: "anime",
    subcategory: "Anime Posters",
    tag: null,
    image: "https://images.unsplash.com/photo-1541562232579-512a21360020?w=400&h=500&fit=crop",
    description: "Premium Itachi Uchiha poster with Sharingan design. A collector's piece.",
  },
  {
    id: 4,
    name: "Sailor Moon — Crystal",
    price: 549,
    category: "anime",
    subcategory: "Anime Posters",
    tag: "New",
    image: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=400&h=500&fit=crop",
    description: "Sailor Moon Crystal poster with vibrant colors and premium print quality.",
  },
  // Football Posters
  {
    id: 5,
    name: "Ronaldo — CR7 Legacy",
    price: 649,
    category: "football",
    subcategory: "Football Posters",
    tag: "Bestseller",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=500&fit=crop",
    description: "Premium Cristiano Ronaldo poster capturing his iconic celebration moments.",
  },
  {
    id: 6,
    name: "Messi — Golden Era",
    price: 649,
    category: "football",
    subcategory: "Football Posters",
    tag: null,
    image: "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=400&h=500&fit=crop",
    description: "Lionel Messi poster celebrating his golden career and World Cup triumph.",
  },
  // Cricket Posters
  {
    id: 7,
    name: "Virat Kohli — King",
    price: 599,
    category: "cricket",
    subcategory: "Cricket Posters",
    tag: "Bestseller",
    image: "https://images.unsplash.com/photo-1540747913346-19212a4c4b43?w=400&h=500&fit=crop",
    description: "Iconic Virat Kohli poster — the King of Cricket in his prime.",
  },
  {
    id: 8,
    name: "MS Dhoni — Captain Cool",
    price: 599,
    category: "cricket",
    subcategory: "Cricket Posters",
    tag: "New",
    image: "https://images.unsplash.com/photo-1593766827959-28afc4d5f4b0?w=400&h=500&fit=crop",
    description: "MS Dhoni — the legendary Captain Cool who led India to glory.",
  },
  // Supercars
  {
    id: 9,
    name: "Ferrari SF90 — Prancing Horse",
    price: 749,
    category: "supercar",
    subcategory: "Supercar/Bikes",
    tag: "Premium",
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=400&h=500&fit=crop",
    description: "Ferrari SF90 Stradale — the pinnacle of Italian engineering and design.",
  },
  {
    id: 10,
    name: "Lamborghini Huracán — Raging Bull",
    price: 749,
    category: "supercar",
    subcategory: "Supercar/Bikes",
    tag: "Premium",
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400&h=500&fit=crop",
    description: "Lamborghini Huracán poster — raw power meets Italian artistry.",
  },
  // Bikes
  {
    id: 11,
    name: "Ducati Panigale — Red Devil",
    price: 649,
    category: "bikes",
    subcategory: "Supercar/Bikes",
    tag: null,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=500&fit=crop",
    description: "Ducati Panigale V4 — the most beautiful superbike ever made.",
  },
  // Movies / TV
  {
    id: 12,
    name: "Breaking Bad — Heisenberg",
    price: 499,
    category: "movies",
    subcategory: "T.V Series/Movies Posters",
    tag: "Cult Classic",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=500&fit=crop",
    description: "Breaking Bad — Heisenberg minimalist poster. Say my name.",
  },
  {
    id: 13,
    name: "The Dark Knight — Joker",
    price: 549,
    category: "movies",
    subcategory: "T.V Series/Movies Posters",
    tag: "Cult Classic",
    image: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=500&fit=crop",
    description: "The Dark Knight — iconic Joker poster. Why so serious?",
  },
  // Music
  {
    id: 14,
    name: "Pink Floyd — The Wall",
    price: 499,
    category: "music",
    subcategory: "Music Posters",
    tag: null,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=500&fit=crop",
    description: "Pink Floyd — The Wall. A timeless piece of rock history.",
  },
  // Motivational
  {
    id: 15,
    name: "Born to Dominate",
    price: 399,
    category: "motivational",
    subcategory: "Quotes Posters",
    tag: "New",
    image: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400&h=500&fit=crop",
    description: "High-energy motivational poster — Born to Dominate. Perfect for gym and office.",
  },
  {
    id: 16,
    name: "Fear The Fire",
    price: 399,
    category: "motivational",
    subcategory: "Quotes Posters",
    tag: null,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=500&fit=crop",
    description: "Fear The Fire — a bold motivational poster for the relentless.",
  },
];

export default products;